# Site settings
title: Orcas - Oracle adaptive/agile schemas
subtitle: Oracle adaptive/agile schemas
description: >
 Orcas ist ein Open Source Deploymentframework mit dem ein bestehendes Datenbankschema in einen in Orcas
 beschriebenen Soll-Zustand geführt werden kann. Orcas steht für Oracle adaptive/agile schemas und
 ist nur mit Oracle RDBMS kompatibel.
twitter_username: OC_WIRE
github_username:  opitzconsulting/Orcas
github_issues: https://github.com/opitzconsulting/orcas/issues
github_fork: https://github.com/opitzconsulting/orcas/fork

# Build settings
baseurl: /orcas
permalink: docs/:title
markdown: kramdown
highlighter: pygments
relative_permalinks: false
collections:
  docs:
    output: true
